# Testing the Artifact 

Here, we are doing some basic testing of the artifact to ensure there aren't any red flags. I plan to: 

1. Ensure there isn't any missing data 
2. Ensure that there are numbers (not other data types/strings) 
3. Print the max and min value to ensure they look about as expected

In [1]:
from vivarium import Artifact 
import pandas as pd, numpy as np, os

In [2]:
art = Artifact('/ihme/homes/vionma5/vivarium_gates_nutrition_optimization/test_artifacts/nigeria.hdf')

In [3]:
def too_many_draws(key): 
    artifact = art.load(key)
    if 'draw_672' in artifact.columns:
        print(f'{key} includes too many draws!')
    return

def too_many_years(key):
    artifact = art.load(key).reset_index()
    if 'year_start' in artifact.columns: 
        if 2000 in artifact.year_start: 
            print(f'{key} includes too many years')

def check_missingness(key):
    artifact = art.load(key)
    if artifact.isnull().values.any(): 
        print(f'{key} includes missing data')
    return


def check_numbers(key):
    artifact = art.load(key)
    if pd.DataFrame(artifact.dtypes != 'float64').values.any():
        print(f'{key} contains non-float type data')
    return 

def print_max_min(key):
    artifact = art.load(key).reset_index()
    maxi = artifact[[col for col in artifact if col.startswith("draw_")]].max()
    maxi = maxi.max()
    mini = artifact[[col for col in artifact if col.startswith("draw_")]].min()
    mini = mini.min()
    print(f'{key} has a max of {maxi} and a min of {mini}')
    return

In [4]:
keys_list = art.keys[3:]
keys_list

['population.structure',
 'population.age_bins',
 'population.demographic_dimensions',
 'population.theoretical_minimum_risk_life_expectancy',
 'covariate.age_specific_fertility_rate.estimate',
 'covariate.stillbirth_20_weeks_to_live_birth_ratio.estimate',
 'cause.maternal_abortion_and_miscarriage.raw_incidence_rate',
 'cause.ectopic_pregnancy.raw_incidence_rate',
 'risk_factor.low_birth_weight_and_short_gestation.exposure',
 'risk_factor.low_birth_weight_and_short_gestation.distribution',
 'risk_factor.low_birth_weight_and_short_gestation.categories',
 'cause.maternal_disorders.raw_incidence_rate',
 'cause.maternal_disorders.incident_probability',
 'cause.maternal_disorders.cause_specific_mortality_rate',
 'cause.maternal_disorders.mortality_probability',
 'cause.maternal_disorders.ylds',
 'risk_factor.hemoglobin_on_maternal_disorder.relative_risk',
 'risk_factor.hemoglobin_on_maternal_disorder.paf',
 'cause.maternal_hemorrhage.raw_incidence_rate',
 'cause.maternal_hemorrhage.cause_specific_mortality_rate',
 'cause.maternal_hemorrhage.incident_probability',
 'risk_factor.hemoglobin_on_maternal_hemorrhage.relative_risk',
 'risk_factor.hemoglobin_on_maternal_hemorrhage.paf',
 'covariate.moderate_hemorrhage_probability.estimate',
 'risk_factor.hemoglobin.mean',
 'risk_factor.hemoglobin.standard_deviation',
 'risk_factor.hemoglobin.pregnant_proportion_below_70_gL',
 'maternal_bmi.prevalance_low_bmi_anemic',
 'maternal_bmi.prevalence_low_bmi_non_anemic',
 'maternal_interventions.ifa_coverage',
 'maternal_interventions.ifa_effect_size',
 'maternal_interventions.mms_stillbirth_rr',
 'maternal_interventions.bep_stillbirth_rr']

In [5]:
for key in keys_list:
    if key in ['risk_factor.low_birth_weight_and_short_gestation.distribution','risk_factor.low_birth_weight_and_short_gestation.categories']:
        print(f'Manually check {key}')
    else: 
        too_many_draws(key)
        #too_many_years(key)
        check_missingness(key)
        #check_numbers(key)
        #print_max_min(key)

Manually check risk_factor.low_birth_weight_and_short_gestation.distribution
Manually check risk_factor.low_birth_weight_and_short_gestation.categories
risk_factor.hemoglobin_on_maternal_hemorrhage.paf includes missing data

In [6]:
test = art.load('maternal_interventions.ifa_coverage')
test

draw,draw_0,draw_1,draw_2,draw_3,draw_4,draw_5,draw_6,draw_7,draw_8,draw_9,...,draw_240,draw_241,draw_242,draw_243,draw_244,draw_245,draw_246,draw_247,draw_248,draw_249
value,0.60278,0.620032,0.61613,0.637985,0.648947,0.594808,0.593139,0.586901,0.61732,0.59592,...,0.627858,0.664803,0.630766,0.618164,0.597913,0.635428,0.635004,0.605042,0.634584,0.61634

In [7]:
test = art.load('risk_factor.low_birth_weight_and_short_gestation.distribution')
test

'ordered_polytomous'

In [8]:
test = art.load('risk_factor.low_birth_weight_and_short_gestation.categories')
test

{'cat2': 'Neonatal preterm and LBWSG (estimation years) - [0, 24) wks, [0, 500) g',
 'cat8': 'Neonatal preterm and LBWSG (estimation years) - [0, 24) wks, [500, 1000) g',
 'cat10': 'Neonatal preterm and LBWSG (estimation years) - [24, 26) wks, [500, 1000) g',
 'cat11': 'Neonatal preterm and LBWSG (estimation years) - [26, 28) wks, [500, 1000) g',
 'cat14': 'Neonatal preterm and LBWSG (estimation years) - [30, 32) wks, [500, 1000) g',
 'cat15': 'Neonatal preterm and LBWSG (estimation years) - [28, 30) wks, [500, 1000) g',
 'cat17': 'Neonatal preterm and LBWSG (estimation years) - [26, 28) wks, [1000, 1500) g',
 'cat19': 'Neonatal preterm and LBWSG (estimation years) - [34, 36) wks, [1000, 1500) g',
 'cat20': 'Neonatal preterm and LBWSG (estimation years) - [28, 30) wks, [1500, 2000) g',
 'cat21': 'Neonatal preterm and LBWSG (estimation years) - [28, 30) wks, [1000, 1500) g',
 'cat22': 'Neonatal preterm and LBWSG (estimation years) - [32, 34) wks, [1000, 1500) g',
 'cat23': 'Neonatal preterm and LBWSG (estimation years) - [30, 32) wks, [1000, 1500) g',
 'cat24': 'Neonatal preterm and LBWSG (estimation years) - [37, 38) wks, [1500, 2000) g',
 'cat25': 'Neonatal preterm and LBWSG (estimation years) - [36, 37) wks, [1500, 2000) g',
 'cat26': 'Neonatal preterm and LBWSG (estimation years) - [30, 32) wks, [2000, 2500) g',
 'cat27': 'Neonatal preterm and LBWSG (estimation years) - [30, 32) wks, [1500, 2000) g',
 'cat28': 'Neonatal preterm and LBWSG (estimation years) - [34, 36) wks, [1500, 2000) g',
 'cat29': 'Neonatal preterm and LBWSG (estimation years) - [32, 34) wks, [1500, 2000) g',
 'cat30': 'Neonatal preterm and LBWSG (estimation years) - [32, 34) wks, [2000, 2500) g',
 'cat31': 'Neonatal preterm and LBWSG (estimation years) - [40, 42+] wks, [2000, 2500) g',
 'cat32': 'Neonatal preterm and LBWSG (estimation years) - [38, 40) wks, [2000, 2500) g',
 'cat33': 'Neonatal preterm and LBWSG (estimation years) - [32, 34) wks, [2500, 3000) g',
 'cat34': 'Neonatal preterm and LBWSG (estimation years) - [34, 36) wks, [2000, 2500) g',
 'cat35': 'Neonatal preterm and LBWSG (estimation years) - [37, 38) wks, [2000, 2500) g',
 'cat36': 'Neonatal preterm and LBWSG (estimation years) - [36, 37) wks, [2000, 2500) g',
 'cat37': 'Neonatal preterm and LBWSG (estimation years) - [34, 36) wks, [2500, 3000) g',
 'cat38': 'Neonatal preterm and LBWSG (estimation years) - [34, 36) wks, [4000, 9999] g',
 'cat39': 'Neonatal preterm and LBWSG (estimation years) - [34, 36) wks, [3000, 3500) g',
 'cat40': 'Neonatal preterm and LBWSG (estimation years) - [36, 37) wks, [2500, 3000) g',
 'cat41': 'Neonatal preterm and LBWSG (estimation years) - [34, 36) wks, [3500, 4000) g',
 'cat42': 'Neonatal preterm and LBWSG (estimation years) - [37, 38) wks, [2500, 3000) g',
 'cat43': 'Neonatal preterm and LBWSG (estimation years) - [40, 42+] wks, [2500, 3000) g',
 'cat44': 'Neonatal preterm and LBWSG (estimation years) - [38, 40) wks, [2500, 3000) g',
 'cat45': 'Neonatal preterm and LBWSG (estimation years) - [36, 37) wks, [3000, 3500) g',
 'cat46': 'Neonatal preterm and LBWSG (estimation years) - [36, 37) wks, [4000, 9999] g',
 'cat47': 'Neonatal preterm and LBWSG (estimation years) - [36, 37) wks, [3500, 4000) g',
 'cat48': 'Neonatal preterm and LBWSG (estimation years) - [37, 38) wks, [3000, 3500) g',
 'cat49': 'Neonatal preterm and LBWSG (estimation years) - [37, 38) wks, [4000, 9999] g',
 'cat50': 'Neonatal preterm and LBWSG (estimation years) - [37, 38) wks, [3500, 4000) g',
 'cat51': 'Neonatal preterm and LBWSG (estimation years) - [40, 42+] wks, [3000, 3500) g',
 'cat52': 'Neonatal preterm and LBWSG (estimation years) - [38, 40) wks, [3000, 3500) g',
 'cat53': 'Neonatal preterm and LBWSG (estimation years) - [38, 40) wks, [4000, 9999] g',
 'cat54': 'Neonatal preterm and LBWSG (estimation years) - [38, 40) wks, [3500, 4000) g',
 'cat55': 'Neonatal preterm and LBWSG (estimation years) - [40, 42+] wks, [3500, 4000) g',
 'cat56': 'Neonatal preterm and LBWSG (estimation years) - [40, 42+] wks, [4000, 9999] g',
 'cat80': 'Neonatal preterm and LBWSG (estimation years) - [28, 30) wks, [2000, 2500) g',
 'cat81': 'Neonatal preterm and LBWSG (estimation years) - [28, 30) wks, [2500, 3000) g',
 'cat82': 'Neonatal preterm and LBWSG (estimation years) - [28, 30) wks, [3000, 3500) g',
 'cat88': 'Neonatal preterm and LBWSG (estimation years) - [30, 32) wks, [2500, 3000) g',
 'cat89': 'Neonatal preterm and LBWSG (estimation years) - [30, 32) wks, [3000, 3500) g',
 'cat90': 'Neonatal preterm and LBWSG (estimation years) - [30, 32) wks, [3500, 4000) g',
 'cat95': 'Neonatal preterm and LBWSG (estimation years) - [32, 34) wks, [3000, 3500) g',
 'cat96': 'Neonatal preterm and LBWSG (estimation years) - [32, 34) wks, [3500, 4000) g',
 'cat106': 'Neonatal preterm and LBWSG (estimation years) - [36, 37) wks, [1000, 1500) g',
 'cat116': 'Neonatal preterm and LBWSG (estimation years) - [38, 40) wks, [1000, 1500) g',
 'cat117': 'Neonatal preterm and LBWSG (estimation years) - [38, 40) wks, [1500, 2000) g',
 'cat123': 'Neonatal preterm and LBWSG (estimation years) - [40, 42+] wks, [1500, 2000) g',
 'cat124': 'Neonatal preterm and LBWSG (estimation years) - [37, 38) wks, [1000, 1500) g'}

In [9]:
test = art.load ('risk_factor.hemoglobin_on_maternal_hemorrhage.paf')
test

                                                            draw_0    draw_1  \
location sex    age_start age_end    year_start year_end
Nigeria  Female 0.000000  0.019178   2023       2024      0.000000  0.000000
                0.019178  0.076712   2023       2024      0.000000  0.000000
                0.076712  0.500000   2023       2024      0.000000  0.000000
                0.500000  1.000000   2023       2024      0.000000  0.000000
                1.000000  2.000000   2023       2024      0.000000  0.000000
                2.000000  5.000000   2023       2024      0.000000  0.000000
                5.000000  10.000000  2023       2024      0.000000  0.000000
                10.000000 15.000000  2023       2024      0.000000  0.000000
                15.000000 20.000000  2023       2024      0.024637  0.006670
                20.000000 25.000000  2023       2024      0.023533  0.004864
                25.000000 30.000000  2023       2024      0.022633  0.003789
                30.000000 35.000000  2023       2024      0.032441  0.006034
                35.000000 40.000000  2023       2024      0.026323  0.005226
                40.000000 45.000000  2023       2024      0.034756  0.006612
                45.000000 50.000000  2023       2024      0.022124  0.007708
                50.000000 55.000000  2023       2024      0.013524  0.012198
                55.000000 60.000000  2023       2024      0.029958  0.001827
                60.000000 65.000000  2023       2024      0.000000  0.000000
                65.000000 70.000000  2023       2024      0.000000  0.000000
                70.000000 75.000000  2023       2024      0.000000  0.000000
                75.000000 80.000000  2023       2024      0.000000  0.000000
                80.000000 85.000000  2023       2024      0.000000  0.000000
                85.000000 90.000000  2023       2024      0.000000  0.000000
                90.000000 95.000000  2023       2024      0.000000  0.000000
                95.000000 125.000000 2023       2024      0.000000  0.000000
         Male   0.000000  0.019178   2023       2024      0.000000  0.000000
                0.019178  0.076712   2023       2024      0.000000  0.000000
                0.076712  0.500000   2023       2024      0.000000  0.000000
                0.500000  1.000000   2023       2024      0.000000  0.000000
                1.000000  2.000000   2023       2024      0.000000  0.000000
                2.000000  5.000000   2023       2024      0.000000  0.000000
                5.000000  10.000000  2023       2024      0.000000  0.000000
                10.000000 15.000000  2023       2024      0.000000  0.000000
                15.000000 20.000000  2023       2024      0.024637  0.006670
                20.000000 25.000000  2023       2024      0.023533  0.004864
                25.000000 30.000000  2023       2024      0.022633  0.003789
                30.000000 35.000000  2023       2024      0.032441  0.006034
                35.000000 40.000000  2023       2024      0.026323  0.005226
                40.000000 45.000000  2023       2024      0.034756  0.006612
                45.000000 50.000000  2023       2024      0.022124  0.007708
                50.000000 55.000000  2023       2024      0.013524  0.012198
                55.000000 60.000000  2023       2024      0.029958  0.001827
                60.000000 65.000000  2023       2024      0.000000  0.000000
                65.000000 70.000000  2023       2024      0.000000  0.000000
                70.000000 75.000000  2023       2024      0.000000  0.000000
                75.000000 80.000000  2023       2024      0.000000  0.000000
                80.000000 85.000000  2023       2024      0.000000  0.000000
                85.000000 90.000000  2023       2024      0.000000  0.000000
                90.000000 95.000000  2023       2024      0.000000  0.000000
                95.000000 125.000000 2023       2024      0.000000  0.000000

                                                           draw_10  draw_100  \
location sex    age_start age_end    year_start year_end
Nigeria  Female 0.000000  0.019178   2023       2024      0.000000  0.000000
                0.019178  0.076712   2023       2024      0.000000  0.000000
                0.076712  0.500000   2023       2024      0.000000  0.000000
                0.500000  1.000000   2023       2024      0.000000  0.000000
                1.000000  2.000000   2023       2024      0.000000  0.000000
                2.000000  5.000000   2023       2024      0.000000  0.000000
                5.000000  10.000000  2023       2024      0.000000  0.000000
                10.000000 15.000000  2023       2024      0.000000  0.000000
                15.000000 20.000000  2023       2024      0.144519  0.069627
                20.000000 25.000000  2023       2024      0.139980  0.046767
                25.000000 30.000000  2023       2024      0.150343  0.054634
                30.000000 35.000000  2023       2024      0.121352  0.065630
                35.000000 40.000000  2023       2024      0.115779  0.055623
                40.000000 45.000000  2023       2024      0.177792  0.057673
                45.000000 50.000000  2023       2024      0.096693  0.045460
                50.000000 55.000000  2023       2024      0.129299  0.095044
                55.000000 60.000000  2023       2024      0.186527  0.113685
                60.000000 65.000000  2023       2024      0.000000  0.000000
                65.000000 70.000000  2023       2024      0.000000  0.000000
                70.000000 75.000000  2023       2024      0.000000  0.000000
                75.000000 80.000000  2023       2024      0.000000  0.000000
                80.000000 85.000000  2023       2024      0.000000  0.000000
                85.000000 90.000000  2023       2024      0.000000  0.000000
                90.000000 95.000000  2023       2024      0.000000  0.000000
                95.000000 125.000000 2023       2024      0.000000  0.000000
         Male   0.000000  0.019178   2023       2024      0.000000  0.000000
                0.019178  0.076712   2023       2024      0.000000  0.000000
                0.076712  0.500000   2023       2024      0.000000  0.000000
                0.500000  1.000000   2023       2024      0.000000  0.000000
                1.000000  2.000000   2023       2024      0.000000  0.000000
                2.000000  5.000000   2023       2024      0.000000  0.000000
                5.000000  10.000000  2023       2024      0.000000  0.000000
                10.000000 15.000000  2023       2024      0.000000  0.000000
                15.000000 20.000000  2023       2024      0.144519  0.069627
                20.000000 25.000000  2023       2024      0.139980  0.046767
                25.000000 30.000000  2023       2024      0.150343  0.054634
                30.000000 35.000000  2023       2024      0.121352  0.065630
                35.000000 40.000000  2023       2024      0.115779  0.055623
                40.000000 45.000000  2023       2024      0.177792  0.057673
                45.000000 50.000000  2023       2024      0.096693  0.045460
                50.000000 55.000000  2023       2024      0.129299  0.095044
                55.000000 60.000000  2023       2024      0.186527  0.113685
                60.000000 65.000000  2023       2024      0.000000  0.000000
                65.000000 70.000000  2023       2024      0.000000  0.000000
                70.000000 75.000000  2023       2024      0.000000  0.000000
                75.000000 80.000000  2023       2024      0.000000  0.000000
                80.000000 85.000000  2023       2024      0.000000  0.000000
                85.000000 90.000000  2023       2024      0.000000  0.000000
                90.000000 95.000000  2023       2024      0.000000  0.000000
                95.000000 125.000000 2023       2024      0.000000  0.000000

                                                          draw_101  draw_102  \
location sex    age_start age_end    year_start year_end
Nigeria  Female 0.000000  0.019178   2023       2024      0.000000  0.000000
                0.019178  0.076712   2023       2024      0.000000  0.000000
                0.076712  0.500000   2023       2024      0.000000  0.000000
                0.500000  1.000000   2023       2024      0.000000  0.000000
                1.000000  2.000000   2023       2024      0.000000  0.000000
                2.000000  5.000000   2023       2024      0.000000  0.000000
                5.000000  10.000000  2023       2024      0.000000  0.000000
                10.000000 15.000000  2023       2024      0.000000  0.000000
                15.000000 20.000000  2023       2024      0.056597  0.039544
                20.000000 25.000000  2023       2024      0.053549  0.056230
                25.000000 30.000000  2023       2024      0.050619  0.026379
                30.000000 35.000000  2023       2024      0.036050  0.042579
                35.000000 40.000000  2023       2024      0.035800  0.023099
                40.000000 45.000000  2023       2024      0.045736  0.038816
                45.000000 50.000000  2023       2024      0.066730  0.042810
                50.000000 55.000000  2023       2024      0.068257  0.035378
                55.000000 60.000000  2023       2024      0.031910  0.044318
                60.000000 65.000000  2023       2024      0.000000  0.000000
                65.000000 70.000000  2023       2024      0.000000  0.000000
                70.000000 75.000000  2023       2024      0.000000  0.000000
                75.000000 80.000000  2023       2024      0.000000  0.000000
                80.000000 85.000000  2023       2024      0.000000  0.000000
                85.000000 90.000000  2023       2024      0.000000  0.000000
                90.000000 95.000000  2023       2024      0.000000  0.000000
                95.000000 125.000000 2023       2024      0.000000  0.000000
         Male   0.000000  0.019178   2023       2024      0.000000  0.000000
                0.019178  0.076712   2023       2024      0.000000  0.000000
                0.076712  0.500000   2023       2024      0.000000  0.000000
                0.500000  1.000000   2023       2024      0.000000  0.000000
                1.000000  2.000000   2023       2024      0.000000  0.000000
                2.000000  5.000000   2023       2024      0.000000  0.000000
                5.000000  10.000000  2023       2024      0.000000  0.000000
                10.000000 15.000000  2023       2024      0.000000  0.000000
                15.000000 20.000000  2023       2024      0.056597  0.039544
                20.000000 25.000000  2023       2024      0.053549  0.056230
                25.000000 30.000000  2023       2024      0.050619  0.026379
                30.000000 35.000000  2023       2024      0.036050  0.042579
                35.000000 40.000000  2023       2024      0.035800  0.023099
                40.000000 45.000000  2023       2024      0.045736  0.038816
                45.000000 50.000000  2023       2024      0.066730  0.042810
                50.000000 55.000000  2023       2024      0.068257  0.035378
                55.000000 60.000000  2023       2024      0.031910  0.044318
                60.000000 65.000000  2023       2024      0.000000  0.000000
                65.000000 70.000000  2023       2024      0.000000  0.000000
                70.000000 75.000000  2023       2024      0.000000  0.000000
                75.000000 80.000000  2023       2024      0.000000  0.000000
                80.000000 85.000000  2023       2024      0.000000  0.000000
                85.000000 90.000000  2023       2024      0.000000  0.000000
                90.000000 95.000000  2023       2024      0.000000  0.000000
                95.000000 125.000000 2023       2024      0.000000  0.000000

                                                          draw_103  draw_104  \
location sex    age_start age_end    year_start year_end
Nigeria  Female 0.000000  0.019178   2023       2024      0.000000  0.000000
                0.019178  0.076712   2023       2024      0.000000  0.000000
                0.076712  0.500000   2023       2024      0.000000  0.000000
                0.500000  1.000000   2023       2024      0.000000  0.000000
                1.000000  2.000000   2023       2024      0.000000  0.000000
                2.000000  5.000000   2023       2024      0.000000  0.000000
                5.000000  10.000000  2023       2024      0.000000  0.000000
                10.000000 15.000000  2023       2024      0.000000  0.000000
                15.000000 20.000000  2023       2024     -0.000662  0.000946
                20.000000 25.000000  2023       2024     -0.001093  0.000911
                25.000000 30.000000  2023       2024     -0.001022  0.001057
                30.000000 35.000000  2023       2024     -0.000619  0.000948
                35.000000 40.000000  2023       2024     -0.001272  0.001264
                40.000000 45.000000  2023       2024     -0.000971  0.000942
                45.000000 50.000000  2023       2024     -0.000962  0.000705
                50.000000 55.000000  2023       2024     -0.000418  0.000579
                55.000000 60.000000  2023       2024     -0.004157  0.000933
                60.000000 65.000000  2023       2024      0.000000  0.000000
                65.000000 70.000000  2023       2024      0.000000  0.000000
                70.000000 75.000000  2023       2024      0.000000  0.000000
                75.000000 80.000000  2023       2024      0.000000  0.000000
                80.000000 85.000000  2023       2024      0.000000  0.000000
                85.000000 90.000000  2023       2024      0.000000  0.000000
                90.000000 95.000000  2023       2024      0.000000  0.000000
                95.000000 125.000000 2023       2024      0.000000  0.000000
         Male   0.000000  0.019178   2023       2024      0.000000  0.000000
                0.019178  0.076712   2023       2024      0.000000  0.000000
                0.076712  0.500000   2023       2024      0.000000  0.000000
                0.500000  1.000000   2023       2024      0.000000  0.000000
                1.000000  2.000000   2023       2024      0.000000  0.000000
                2.000000  5.000000   2023       2024      0.000000  0.000000
                5.000000  10.000000  2023       2024      0.000000  0.000000
                10.000000 15.000000  2023       2024      0.000000  0.000000
                15.000000 20.000000  2023       2024     -0.000662  0.000946
                20.000000 25.000000  2023       2024     -0.001093  0.000911
                25.000000 30.000000  2023       2024     -0.001022  0.001057
                30.000000 35.000000  2023       2024     -0.000619  0.000948
                35.000000 40.000000  2023       2024     -0.001272  0.001264
                40.000000 45.000000  2023       2024     -0.000971  0.000942
                45.000000 50.000000  2023       2024     -0.000962  0.000705
                50.000000 55.000000  2023       2024     -0.000418  0.000579
                55.000000 60.000000  2023       2024     -0.004157  0.000933
                60.000000 65.000000  2023       2024      0.000000  0.000000
                65.000000 70.000000  2023       2024      0.000000  0.000000
                70.000000 75.000000  2023       2024      0.000000  0.000000
                75.000000 80.000000  2023       2024      0.000000  0.000000
                80.000000 85.000000  2023       2024      0.000000  0.000000
                85.000000 90.000000  2023       2024      0.000000  0.000000
                90.000000 95.000000  2023       2024      0.000000  0.000000
                95.000000 125.000000 2023       2024      0.000000  0.000000

                                                          draw_105  draw_106  \
location sex    age_start age_end    year_start year_end
Nigeria  Female 0.000000  0.019178   2023       2024      0.000000  0.000000
                0.019178  0.076712   2023       2024      0.000000  0.000000
                0.076712  0.500000   2023       2024      0.000000  0.000000
                0.500000  1.000000   2023       2024      0.000000  0.000000
                1.000000  2.000000   2023       2024      0.000000  0.000000
                2.000000  5.000000   2023       2024      0.000000  0.000000
                5.000000  10.000000  2023       2024      0.000000  0.000000
                10.000000 15.000000  2023       2024      0.000000  0.000000
                15.000000 20.000000  2023       2024      0.048662  0.034327
                20.000000 25.000000  2023       2024      0.056953  0.037850
                25.000000 30.000000  2023       2024      0.037847  0.029445
                30.000000 35.000000  2023       2024      0.052471  0.043974
                35.000000 40.000000  2023       2024      0.022048  0.034468
                40.000000 45.000000  2023       2024      0.024929  0.027451
                45.000000 50.000000  2023       2024      0.039044  0.036535
                50.000000 55.000000  2023       2024      0.118174  0.032905
                55.000000 60.000000  2023       2024      0.013809  0.055756
                60.000000 65.000000  2023       2024      0.000000  0.000000
                65.000000 70.000000  2023       2024      0.000000  0.000000
                70.000000 75.000000  2023       2024      0.000000  0.000000
                75.000000 80.000000  2023       2024      0.000000  0.000000
                80.000000 85.000000  2023       2024      0.000000  0.000000
                85.000000 90.000000  2023       2024      0.000000  0.000000
                90.000000 95.000000  2023       2024      0.000000  0.000000
                95.000000 125.000000 2023       2024      0.000000  0.000000
         Male   0.000000  0.019178   2023       2024      0.000000  0.000000
                0.019178  0.076712   2023       2024      0.000000  0.000000
                0.076712  0.500000   2023       2024      0.000000  0.000000
                0.500000  1.000000   2023       2024      0.000000  0.000000
                1.000000  2.000000   2023       2024      0.000000  0.000000
                2.000000  5.000000   2023       2024      0.000000  0.000000
                5.000000  10.000000  2023       2024      0.000000  0.000000
                10.000000 15.000000  2023       2024      0.000000  0.000000
                15.000000 20.000000  2023       2024      0.048662  0.034327
                20.000000 25.000000  2023       2024      0.056953  0.037850
                25.000000 30.000000  2023       2024      0.037847  0.029445
                30.000000 35.000000  2023       2024      0.052471  0.043974
                35.000000 40.000000  2023       2024      0.022048  0.034468
                40.000000 45.000000  2023       2024      0.024929  0.027451
                45.000000 50.000000  2023       2024      0.039044  0.036535
                50.000000 55.000000  2023       2024      0.118174  0.032905
                55.000000 60.000000  2023       2024      0.013809  0.055756
                60.000000 65.000000  2023       2024      0.000000  0.000000
                65.000000 70.000000  2023       2024      0.000000  0.000000
                70.000000 75.000000  2023       2024      0.000000  0.000000
                75.000000 80.000000  2023       2024      0.000000  0.000000
                80.000000 85.000000  2023       2024      0.000000  0.000000
                85.000000 90.000000  2023       2024      0.000000  0.000000
                90.000000 95.000000  2023       2024      0.000000  0.000000
                95.000000 125.000000 2023       2024      0.000000  0.000000
